// Auth 
export const AUTH_USER_MANAGEMENT = 'AUTH.USER_MANAGEMENT';
export const AUTH_PERMISSION_MANAGEMENT = 'AUTH.PERMISSION_MANAGEMENT';

// CMS
export const CMS_SETTINGS_MANAGEMENT = "CMS.SETTINGS_MANAGEMENT";
export const CMS_ARTICLE_MANAGEMENT = "CMS.ARTICLE_MANAGEMENT";
export const CMS_TOPIC_MANAGEMENT = "CMS.TOPIC_MANAGEMENT";
export const CMS_TAG_MANAGEMENT = "CMS.TAG_MANAGEMENT";
export const CMS_PAGE_MANAGEMENT = "CMS.PAGE_MANAGEMENT";
export const CMS_LINK_MANAGEMENT = "CMS.LINK_MANAGEMENT";
export const CMS_LINK_SECTION_MANAGEMENT = "CMS.LINK_SECTION_MANAGEMENT";
export const CMS_MENU_MANAGEMENT = "CMS.MENU_MANAGEMENT";
export const CMS_SLIDESHOW_MANAGEMENT = "CMS.SLIDESHOW_MANAGEMENT";

// CRM
export const CRM_SETTING_MANAGMENT = "CRM.SETTING_MANAGMENT";
export const CRM_ALL_MESSAGE_MANAGMENT = "CRM.ALL_MESSAGE_MANAGMENT";
export const CRM_MESSAGE_MANAGMENT = "CRM.MESSAGE_MANAGMENT";
export const CRM_ALL_EMAIL_INBOX_MANAGMENT = "CRM.ALL_EMAIL_INBOX_MANAGMENT";
export const CRM_EMAIL_INBOX_MANAGMENT = "CRM.EMAIL_INBOX_MANAGMENT";
export const CRM_ALL_EMAIL_OUTBOX_MANAGMENT = "CRM.ALL_EMAIL_OUTBOX_MANAGMENT";
export const CRM_EMAIL_OUTBOX_MANAGMENT = "CRM.EMAIL_OUTBOX_MANAGMENT";
export const CRM_SUBSCRIBE_MANAGMENT = "CRM.SUBSCRIBE_MANAGMENT";

// SALE
export const SALE_CATEGORY_MANAGEMENT = "SALE.CATEGORY_MANAGEMENT";
export const SALE_PRODUCT_ATTRIBUTE_MANAGEMENT = "SALE.PRODUCT_ATTRIBUTE_MANAGEMENT";
export const SALE_ORDER_MANAGEMENT = "SALE.ORDER_MANAGEMENT";
export const SALE_ORDER_DISCOUNT_MANAGEMENT = "SALE.ORDER_DISCOUNT_MANAGEMENT";
export const SALE_ORDER_ITEM_MANAGEMENT = "SALE.ORDER_ITEM_MANAGEMENT";
export const SALE_ORDERNOTE_MANAGEMENT = "SALE.ORDERNOTE_MANAGEMENT";
export const SALE_PAYMENT_MANAGEMENT = "SALE.PAYMENT_MANAGEMENT";
export const SALE_PRODUCT_MANAGEMENT = "SALE.PRODUCT_MANAGEMENT";
export const SALE_PRODUCT_INVENTORY_MANAGEMENT = "SALE.PRODUCT_INVENTORY_MANAGEMENT";
export const SALE_PRODUCT_REVIEW_MANAGEMENT = "SALE.PRODUCT_REVIEW_MANAGEMENT";
export const SALE_PRODUCT_REVIEW_HELPFULNESS_MANAGEMENT = "SALE.PRODUCT_REVIEW_HELPFULNESS_MANAGEMENT";
export const SALE_PRODUCT_TAG_MANAGEMENT = "SALE.PRODUCT_TAG_MANAGEMENT";
export const SALE_BASE_INFORMATION_MANAGEMENT = "SALE.BASE_INFORMATION_MANAGEMENT";
export const SALE_SEARCH_TERM_MANAGEMENT = "SALE.SEARCH_TERM_MANAGEMENT";
export const SALE_SHIPMENT_MANAGEMENT = "SALE.SHIPMENT_MANAGEMENT";
export const SALE_SHOPPING_CART_MANAGEMENT = "SALE.SHOPPING_CART_MANAGEMENT";
export const SALE_CURRENCY_MANAGEMENT = "SALE.CURRENCY_MANAGEMENT";
export const SALE_DELIVERY_MANAGEMENT = "SALE.DELIVERY_MANAGEMENT";
export const SALE_DISCOUNT_MANAGEMENT = "SALE.DISCOUNT_MANAGEMENT";
export const SALE_MANUFACTURER_MANAGEMENT = "SALE.MANUFACTURER_MANAGEMENT";
export const SALE_SHIPMENT_METHOD_MANAGEMENT = "SALE.SHIPMENT_METHOD_MANAGEMENT";
export const SALE_COUNTRY_MANAGEMENT = "SALE.COUNTRY_MANAGEMENT";
export const SALE_STATE_PROVINCE_MANAGEMENT = "SALE.STATE_PROVINCE_MANAGEMENT";
export const SALE_ADDRESS_MANAGEMENT = "SALE.ADDRESS_MANAGEMENT";
export const SALE_TAX_MANAGEMENT = "SALE.TAX_MANAGEMENT";

// FS
export const FS_GALLEY_VIEW = "FS.FILE_UPLOAD";
export const FS_FILE_UPLOAD = "FS.FILE_UPLOAD";