// Auth 
export const AUTH_USER_MANAGEMENT = 'AUTH.USER_MANAGEMENT';
export const AUTH_PERMISSION_MANAGEMENT = 'AUTH.PERMISSION_MANAGEMENT';

// CMS
export const CMS_SETTINGS_MANAGEMENT = "CMS.SETTINGS_MANAGEMENT";
export const CMS_ARTICLE_MANAGEMENT = "CMS.ARTICLE_MANAGEMENT";
export const CMS_TOPIC_MANAGEMENT = "CMS.TOPIC_MANAGEMENT";
export const CMS_TAG_MANAGEMENT = "CMS.TAG_MANAGEMENT";
export const CMS_PAGE_MANAGEMENT = "CMS.PAGE_MANAGEMENT";
export const CMS_LINK_MANAGEMENT = "CMS.LINK_MANAGEMENT";
export const CMS_LINK_SECTION_MANAGEMENT = "CMS.LINK_SECTION_MANAGEMENT";
export const CMS_MENU_MANAGEMENT = "CMS.MENU_MANAGEMENT";
export const CMS_SLIDESHOW_MANAGEMENT = "CMS.SLIDESHOW_MANAGEMENT";

// CRM
export const CRM_SETTING_MANAGMENT = "CRM.SETTING_MANAGMENT";
export const CRM_ALL_MESSAGE_MANAGMENT = "CRM.ALL_MESSAGE_MANAGMENT";
export const CRM_MESSAGE_MANAGMENT = "CRM.MESSAGE_MANAGMENT";
export const CRM_ALL_EMAIL_INBOX_MANAGMENT = "CRM.ALL_EMAIL_INBOX_MANAGMENT";
export const CRM_EMAIL_INBOX_MANAGMENT = "CRM.EMAIL_INBOX_MANAGMENT";
export const CRM_ALL_EMAIL_OUTBOX_MANAGMENT = "CRM.ALL_EMAIL_OUTBOX_MANAGMENT";
export const CRM_EMAIL_OUTBOX_MANAGMENT = "CRM.EMAIL_OUTBOX_MANAGMENT";
export const CRM_SUBSCRIBE_MANAGMENT = "CRM.SUBSCRIBE_MANAGMENT";

// FS
export const FS_GALLEY_VIEW = "FS.FILE_UPLOAD";
export const FS_FILE_UPLOAD = "FS.FILE_UPLOAD";