export const AUTH_USER_MANAGEMENT = 'AUTH.USER_MANAGEMENT';
export const AUTH_PERMISSION_MANAGEMENT = 'AUTH.PERMISSION_MANAGEMENT';

export const CMS_SETTINGS_MANAGEMENT = "CMS.SETTINGS_MANAGEMENT";
export const CMS_ARTICLE_MANAGEMENT = "CMS.ARTICLE_MANAGEMENT";
export const CMS_TOPIC_MANAGEMENT = "CMS.TOPIC_MANAGEMENT";
export const CMS_TAG_MANAGEMENT = "CMS.TAG_MANAGEMENT";
export const CMS_PAGE_MANAGEMENT = "CMS.PAGE_MANAGEMENT";
export const CMS_LINK_MANAGEMENT = "CMS.LINK_MANAGEMENT";
export const CMS_LINK_SECTION_MANAGEMENT = "CMS.LINK_SECTION_MANAGEMENT";
export const CMS_MENU_MANAGEMENT = "CMS.MENU_MANAGEMENT";
export const CMS_SLIDESHOW_MANAGEMENT = "CMS.SLIDESHOW_MANAGEMENT";